sep24:
  #  Port this server is being ran on
  port: 8091
  #  URL for anchor platform server
  anchorPlatformUrl: "http://localhost:8080"
  #  URL for horizon server
  horizonUrl: "https://horizon-testnet.stellar.org"
  #  Secret key used to send funds to user accounts
  secret: "SA4254A5HI42PDSOTDEWE24VFGKO7JACKHUNM4DCB3YTJVUZ4TL57LH3"
  # When true, enables test endpoints
  enableTest: true
  # Encryption key for interactive JWT
  interactiveJwtKey: "SA4254A5HI42PDSOTDEWE24VFGKO7JACKHUNM4DCB3YTJVUZ4TL57LH3"