anchor.settings:
  version: 0.0.1
  platformApiEndpoint: http://localhost:8085
  hostUrl: http://localhost:8081
  distributionWallet: GBN4NNCDGJO4XW4KQU3CBIESUJWFVBUZPOKUZHT7W7WRB7CWOA7BXVQF
  distributionWalletMemo:
  distributionWalletMemoType:
  secret: SAJW2O2NH5QMMVWYAN352OEXS2RUY675A2HPK5HEG2FRR2NXPYA4OLYN

integration-auth:
  authType: NONE
  platformToAnchorSecret: myPlatformToAnchorSecret
  anchorToPlatformSecret: myAnchorToPlatformSecret
  expirationMilliseconds: 30000

sep24:
  #  Port this server is being ran on
  port: 8091
  #  URL for anchor platform server
  anchorPlatformUrl: "http://localhost:8085"
  #  URL for horizon server
  horizonUrl: "https://horizon-testnet.stellar.org"
  # Secret key used to send funds to user accounts.
  # Public key: GABCKCYPAGDDQMSCTMSBO7C2L34NU3XXCW7LR4VVSWCCXMAJY3B4YCZP
  secret: "SAJW2O2NH5QMMVWYAN352OEXS2RUY675A2HPK5HEG2FRR2NXPYA4OLYN"
  # When true, enables test endpoints
  enableTest: true
  # Encryption key for interactive JWT
  interactiveJwtKey: "secret_sep24_interactive_url_jwt_secret"