sep24:
  port: 8091
  anchorPlatformUrl: "http://localhost:8080"
  horizonUrl: "https://horizon-testnet.stellar.org"
  secret: "SCQ2YRUGKBO4Q6RWSXV3SYVGHJB525XVKUP2HDGVW3LV42UBLGTZ24XX"
  enableTest: true
  interactiveJwtKey: "sep24 interactive url secret"