openapi: 3.0.0
info:
  version: "0.1"
  title: Event Schemas
  description: |
    This document specifies the schemas used for Events in Stellar Anchor Platform project.
    
    There are currently two types of Events: `QuoteEvent` and `TransactionEvent`. When events occur (quote_created, transaction_created, etc...), the events are published by the Anchor Platform to a queue (Kafka, SQS, ect...) for the Anchor to consume and process.
    
    This differs from the Callbacks API, which defines requests made while the Platform is processing a request from a client application.
tags:
  - name: "Event Schemas"
    description: "Event Schemas for events that are published to a queue for the Anchor to consume."
components:
  schemas:
    QuoteEvent:
      type: object
      properties:
        eventId:
          type: string
        type:
          type: string
          enum:
            - quote_created
          description:
            quote_created - a quote was created via the SEP38 API
        id:
          type: string
        sell_asset:
          type: string
        sell_amount:
          type: string
        buy_asset:
          type: string
        buy_amount:
          type: string
        expires_at:
          type: string
          format: date-time
        price:
          type: string
          description: price without including fees.
        total_price:
          type: string
          description: price including fees.
        creator:
          $ref: '#/components/schemas/StellarId'
        transaction_id:
          type: string
        created_at:
          type: string
          format: date-time
        fee:
          type: object
          properties:
            total:
              type: string
            asset:
              type: string
            details:
              type: array
              items:
                type: object
                properties:
                  name:
                    type: string
                  description:
                    type: string
                  amount:
                    type: string
                required:
                  - name
                  - amount
          required:
            - total
            - asset
      required:
        - eventId
        - type
        - id
        - sell_asset
        - sell_amount
        - buy_asset
        - buy_amount
        - expires_at
        - price
        - total_price
        - created_at
    TransactionEvent:
      type: object
      properties:
        eventId:
          type: string
        type:
          type: string
          enum:
            - transaction_created
            - transaction_status_changed
            - transaction_error
          description:
            transaction_created - a transaction was created via SEP31 ;
            
            transaction_status_changed - a transaction status change happened. The detail of the status change is described in the `status_change` field.
            
            transaction_error - error processing the transaction
        id:
          type: string
        sep:
          type: integer
          enum: [31]
        kind:
          type: string
          enum: ["receive"]
        status:
          type: string
          enum: [
            "pending_sender",
            "pending_stellar",
            "pending_customer_info_update",
            "pending_receiver",
            "pending_external",
            "completed",
            "error"
          ]
        status_change:
          $ref: '#/components/schemas/StatusChange'
        amount_expected:
          $ref: '#/components/schemas/Amount'
        amount_in:
          $ref: '#/components/schemas/Amount'
        amount_out:
          $ref: '#/components/schemas/Amount'
        amount_fee:
          $ref: '#/components/schemas/Amount'
        quote_id:
          type: string
        started_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        completed_at:
          type: string
          format: date-time
        transfer_received_at:
          type: string
          format: date-time
        message:
          type: string
        refunds:
          $ref: '#/components/schemas/Refunds'
        stellar_transactions:
          type: array
          items:
            $ref: '#/components/schemas/StellarTransaction'
        external_transaction_id:
          type: string
        custodial_transaction_id:
          type: string
        source_account:
          type: string
        destination_account:
          type: string
        customers:
          type: object
          properties:
            sender:
              $ref: '#/components/schemas/StellarId'
            receiver:
              $ref: '#/components/schemas/StellarId'
        creator:
          $ref: '#/components/schemas/StellarId'
    Amount:
      type: object
      properties:
        amount:
          type: string
        asset:
          type: string
    StatusChange:
      type: object
      properties:
        from:
          type: string
        to:
          type: string
    Refunds:
      type: object
      properties:
        amount_refunded:
          $ref: '#/components/schemas/Amount'
        amount_fee:
          $ref: '#/components/schemas/Amount'
        payments:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
              id_type:
                type: string
                enum:
                  - stellar
                  - external
              amount:
                $ref: '#/components/schemas/Amount'
              fee:
                $ref: '#/components/schemas/Amount'
              requested_at:
                type: string
                format: date-time
              refunded_at:
                type: string
                format: date-time
    StellarId:
      type: object
      description:
        StellarId's are objects that identify an on-chain entity. Both end users and SEP-31 senders can be identified
        with StellarId's. Id's for SEP-31 senders will never include a `memo` or `memo_type`.
      properties:
        account:
          type: string
          description: Either the Stellar account or Muxed account address of the on-chain entity.
        memo:
          type: string
          description:
            The memo unique identifys the on-chain entity when paired with `StellarId.account`. Memos are not valid if
            `StellarId.account` is a Muxed account.
        memo_type:
          type: string
          description: The type of `StellarId.memo`.
          enum:
            - hash
            - text
            - id
    StellarTransaction:
      type: object
      properties:
        id:
          type: string
        memo:
          type: string
        memo_type:
          type: string
          enum:
            - text
            - hash
            - id
        created_at:
          type: string
          format: date-time
        envelope:
          type: string
        payments:
          type: array
          items:
            type: object
            properties:
              operationId:
                type: string
              source_account:
                type: string
              destination_account:
                type: string
              amount:
                $ref: '#/components/schemas/Amount'