apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.ingress.name }}
  namespace: {{ .Values.namespace }}
  annotations:
    {{- $annotations := dict }}
    {{- if .Values.ingress.annotations }}
      {{- $annotations = merge $annotations .Values.ingress.annotations }}
    {{- end }}
    {{- range $key, $value := $annotations }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
  labels:
    app.kubernetes.io/name: {{ .Values.fullName }}-ingress
    helm.sh/chart: {{ $.Chart.Name }}-{{ $.Chart.Version }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- if .Values.ingress.tls.host }}
    - hosts:
        - {{ .Values.ingress.tls.host }}
    {{- end }}
    {{- if .Values.ingress.tls.secretName }}
      secretName: {{ .Values.ingress.tls.secretName }}
    {{- end }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.rules.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.fullName }}-svc-{{ .Values.services.ui.name }}
                port:
                  number: {{ .Values.services.ui.servicePort | default 3000 }}