version: '2.4'
services:
  platform:
    extends:
      file: common/docker-compose.yaml
      service: platform
    env_file:
      - profiles/${TEST_PROFILE_NAME:-default}/config.env
      - profiles/${TEST_PROFILE_NAME:-default}/test.env
    depends_on:
      - db
      - kafka
      - reference-server
      - sep24-reference-ui

  observer:
    extends:
      file: common/docker-compose.yaml
      service: observer
    env_file:
      - profiles/${TEST_PROFILE_NAME:-default}/config.env
      - profiles/${TEST_PROFILE_NAME:-default}/test.env
    depends_on:
      - db
      - kafka

  reference-server:
    extends:
      file: common/docker-compose.yaml
      service: reference-server
    depends_on:
      - reference-db

  sep24-reference-ui:
    extends:
      file: common/docker-compose.yaml
      service: sep24-reference-ui

  kafka:
    extends:
      file: common/docker-compose.yaml
      service: kafka

  db:
    extends:
      file: common/docker-compose.yaml
      service: db

  reference-db:
    extends:
      file: common/docker-compose.yaml
      service: reference-db
