apiVersion: apps/v1
kind: Deployment
metadata:
  name: ap-reference
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ap-reference
  template:
    metadata:
      labels:
        app: ap-reference
    spec:
      containers:
        - name: reference
          image: anchor-platform:local
          args: [ "--kotlin-reference-server" ]
          imagePullPolicy: Never
          ports:
            - containerPort: 8091
          resources:
            requests:
              memory: 512Mi
              cpu: 500m
            limits:
              memory: 1Gi
              cpu: "1"
          volumeMounts:
            - name: config-volume
              mountPath: /config
              readOnly: true
          env:
            - name: KT_REFERENCE_SERVER_CONFIG
              value: /config/config.yaml
            - name: DATA.USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.fullName }}-secrets
                  key: POSTGRES_USER
            - name: DATA.PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.fullName }}-secrets
                  key: POSTGRES_PASSWORD
            - name: APP.SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.fullName }}-secrets
                  key: SEP6_SECRET
            - name: SEP24.INTERACTIVE_JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.fullName }}-secrets
                  key: SEP24_INTERACTIVE_JWT_KEY
            - name: SEP24.SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.fullName }}-secrets
                  key: SEP24_SECRET
            - name: AUTH.PLATFORM_TO_ANCHOR_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.fullName }}-secrets
                  key: PLATFORM_ANCHOR_SECRET
            - name: AUTH.ANCHOR_TO_PLATFORM_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.fullName }}-secrets
                  key: ANCHOR_PLATFORM_SECRET
            - name: AUTH.EXPIRATION_MILLISECONDS
              value: "30000"
      volumes:
        - name: config-volume
          configMap:
            name: reference-config