apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.fullName }}-secrets
  namespace: {{ .Values.namespace }}
spec:
  secretStoreRef:
    name: {{ .Values.secretStoreRefName }}
    kind: ClusterSecretStore
  target:
    name: {{ .Values.fullName }}-secrets
  data:
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: {{ .Values.namespace }}/{{ .Values.fullName }}-secrets
        property: POSTGRES_PASSWORD
    - secretKey: POSTGRES_USER
      remoteRef:
        key: {{ .Values.namespace }}/{{ .Values.fullName }}-secrets
        property: POSTGRES_USER
    - secretKey: PAYMENT_SIGNING_SEED
      remoteRef:
        key: {{ .Values.namespace }}/{{ .Values.fullName }}-secrets
        property: PAYMENT_SIGNING_SEED
    - secretKey: SEP24_INTERACTIVE_JWT_KEY
      remoteRef:
        key: {{ .Values.namespace }}/{{ .Values.fullName }}-secrets
        property: SEP24_INTERACTIVE_JWT_KEY
    - secretKey: PLATFORM_ANCHOR_SECRET
      remoteRef:
        key: {{ .Values.namespace }}/{{ .Values.fullName }}-secrets
        property: PLATFORM_ANCHOR_SECRET
    - secretKey: ANCHOR_PLATFORM_SECRET
      remoteRef:
        key: {{ .Values.namespace }}/{{ .Values.fullName }}-secrets
        property: ANCHOR_PLATFORM_SECRET