apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.fullName }}-secrets
spec:
  secretStoreRef:
    name: {{ .Values.secretStoreRefName }}
    kind: ClusterSecretStore
  target:
    name: {{ .Values.fullName }}-secrets
  data:
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: anchor-platform/{{ .Values.fullName }}-secrets
        property: POSTGRES_PASSWORD
    - secretKey: POSTGRES_USER
      remoteRef:
        key: anchor-platform/{{ .Values.fullName }}-secrets
        property: POSTGRES_USER
    - secretKey: SEP6_SECRET
      remoteRef:
        key: anchor-platform/{{ .Values.fullName }}-secrets
        property: SEP6_SECRET
    - secretKey: SEP24_INTERACTIVE_JWT_KEY
      remoteRef:
        key: anchor-platform/{{ .Values.fullName }}-secrets
        property: SEP24_INTERACTIVE_JWT_KEY
    - secretKey: SEP24_SECRET
      remoteRef:
        key: anchor-platform/{{ .Values.fullName }}-secrets
        property: SEP24_SECRET
    - secretKey: PLATFORM_ANCHOR_SECRET
      remoteRef:
        key: anchor-platform/{{ .Values.fullName }}-secrets
        property: PLATFORM_ANCHOR_SECRET
    - secretKey: ANCHOR_PLATFORM_SECRET
      remoteRef:
        key: anchor-platform/{{ .Values.fullName }}-secrets
        property: ANCHOR_PLATFORM_SECRET