apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.fullName }}-svc-{{ .Values.services.ref.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- if .Values.services.ref.labels }}
      {{- range $key, $value := .Values.services.ref.labels }}
        {{ $key }}: {{ $value | quote }}
      {{- end }}
    {{- end}}
spec:
  type: {{ .Values.services.ref.type | default "ClusterIP" }}
  ports:
    - protocol: TCP
      port: {{ .Values.services.ref.servicePort | default 8091 }}
      targetPort: {{ .Values.services.ref.containerPort | default 8091 }}
  selector:
    app: {{ .Values.fullName }}-svc-{{ .Values.services.ref.name }}