ALTER TABLE sep6_transaction ADD version INTEGER NOT NULL DEFAULT 0;
ALTER TABLE sep24_transaction ADD version INTEGER NOT NULL DEFAULT 0;
ALTER TABLE sep31_transaction ADD version INTEGER NOT NULL DEFAULT 0;
