apiVersion: v1
appVersion: "1.0"
description: Anchor Platform Reference Server Helm Chart
maintainers:
  - name: Philip Liu
    email: philip.liu@stellar.org
sources:
  - "https://github.com/stellar/java-stellar-anchor-sdk"
name: ap-reference-server
version: 0.1.0