version: 1

sep1:
  toml:
    type: string
    value: |
      ACCOUNTS = []
      VERSION = "0.1.0"
      NETWORK_PASSPHRASE = "Test SDF Network ; September 2015"
      SIGNING_KEY = "GCHLHDBOKG2JWMJQBTLSL5XG6NO7ESXI2TAQKZXCXWXB5WI2X6W233PR"
      WEB_AUTH_ENDPOINT = "http://localhost:8080/auth"
      KYC_SERVER = "http://localhost:8080/sep12"
      DIRECT_PAYMENT_SERVER = "http://localhost:8080/sep31"
      ANCHOR_QUOTE_SERVER = "http://localhost:8080/sep38"
      
      [[CURRENCIES]]
      code = "USDC"
      issuer = "GDQOE23CFSUMSVQK4Y5JHPPYK73VYCNHZHA7ENKCV37P6SUEO6XQBKPP"
      status = "test"
      is_asset_anchored = true
      anchor_asset_type = "fiat"
      desc = "A test USDC issued by Stellar."

assets:
  type: json
  value: |
      {
        "assets": [
          {
            "schema": "stellar",
            "code": "USDC",
            "issuer": "GDQOE23CFSUMSVQK4Y5JHPPYK73VYCNHZHA7ENKCV37P6SUEO6XQBKPP",
            "distribution_account": "GBN4NNCDGJO4XW4KQU3CBIESUJWFVBUZPOKUZHT7W7WRB7CWOA7BXVQF",
            "significant_decimals": 2,
            "send": {
              "fee_fixed": 0,
              "fee_percent": 0,
              "min_amount": 1,
              "max_amount": 1000000
            },
            "sep31" : {
              "quotes_supported": true,
              "quotes_required": false,
              "sep12": {
                "sender": {
                  "types": {
                    "sep31-sender": {
                      "description": "U.S. citizens limited to sending payments of less than $10,000 in value"
                    },
                    "sep31-large-sender": {
                      "description": "U.S. citizens that do not have sending limits"
                    },
                    "sep31-foreign-sender": {
                      "description": "non-U.S. citizens sending payments of less than $10,000 in value"
                    }
                  }
                },
                "receiver": {
                  "types": {
                    "sep31-receiver": {
                      "description": "U.S. citizens receiving USD"
                    },
                    "sep31-foreign-receiver": {
                      "description": "non-U.S. citizens receiving USD"
                    }
                  }
                }
              },
              "fields": {
                "transaction": {
                  "receiver_routing_number": {
                    "description": "routing number of the destination bank account"
                  },
                  "receiver_account_number": {
                    "description": "bank account number of the destination"
                  },
                  "type": {
                    "description": "type of deposit to make",
                    "choices": [
                      "SEPA",
                      "SWIFT"
                    ]
                  }
                }
              }
            },
            "sep38": {
              "exchangeable_assets": [
                "iso4217:USD"
              ]
            },
            "sep31_enabled": true,
            "sep38_enabled": true
          }
        ]
      }

