ACCOUNTS = [ "GAJ3JPQH3ISAZBMRUPKQ6ZQLRXIROCKJKBIYMGPFUEETQEDGFAW4IQ5H" ]
VERSION = "0.1.0"
SIGNING_KEY = "GAJ3JPQH3ISAZBMRUPKQ6ZQLRXIROCKJKBIYMGPFUEETQEDGFAW4IQ5H"
NETWORK_PASSPHRASE = "Test SDF Network ; September 2015"

