wallet:
  #  Port this server is being run on
  port: 8092
  # The hostname of this server
  hostname: "localhost:8092"

anchor:
  # The domain of the anchor server
  domain: "localhost:8080"
  # The endpoint of the anchor server
  endpoint: "http://localhost:8080"

secret:
  key: "SD65QCQAT2V27SEIL3TJSA2PKGYQ5RWZ3IA5MYXJWY223VPYDBIJ4GEB"

toml:
  path: "wallet-reference-server/src/main/resources/toml"