apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.fullName }}-config-env-vars
data:
  {{- range $key, $value := .Values.app_config }}
  {{ include "common.addField" (list $key $value ) }}
  {{- end }}
  {{ include "common.addMultiline" (list "assets.value" .Values.assets_config ) }}
  {{ include "common.addMultiline" (list "sep1.toml.value" .Values.toml_config ) }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.fullName }}
data:
  anchor-config.yaml: |
    version: 1
