apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.fullName }}-svc-{{ .Values.services.observer.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- if .Values.services.observer.labels }}
      {{- range $key, $value := .Values.services.observer.labels }}
        {{ $key }}: {{ $value | quote }}
      {{- end }}
    {{- end}}
    app.kubernetes.io/name: {{ .Values.fullName }}-observer
    helm.sh/chart: {{ $.Chart.Name }}-{{ $.Chart.Version }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.services.observer.type | default "ClusterIP" }}
  ports:
    - protocol: TCP
      port: {{ .Values.services.observer.servicePort | default 8083 }}
      targetPort: {{ .Values.services.observer.containerPort | default 8083 }}
  selector:
    app: ap-observer