#######################################################################
## Anchor Platform - Dev Config
##
## An dev config for Anchor Platform.
## For a list of all config options, see <LINK_TO_DOCUMENTATION>.
#######################################################################

##########################
## System Configuration
##########################
version: 1

data:
  type: h2

# The anchor server callback API endpoint for customer, fee, quote, and unique url integration.
callback_api:
  base_url: https://localhost:8080
  auth_type: NONE

stellar_network:
  # Use `TESTNET` or `PUBNET` network
  network: TESTNET
  horizon_url: https://horizon-testnet.stellar.org
  network_passphrase: 'Test SDF Network ; September 2015'

events:
  enabled: true
  publisher_type: kafka

logging:
  level: INFO

metrics:
  enabled: true

language: en

#######################
## SEP Configuration
#######################
sep1:
  enabled: true
  stellar_file: https://localhost:8080/assets.yaml

sep10:
  enabled: true

sep12:
  enabled: true

sep24:
  enabled: true

sep31:
  enabled: true

sep38:
  enabled: true

#########################
## Assets Configuration
#########################
# Can be specified as external file (`file:assets.yaml`) or in-file
assets:
  type: json
  value: |
  {
    "assets": [
      {
        "schema": "stellar",
        "code": "USDC",
        "issuer": "GDQOE23CFSUMSVQK4Y5JHPPYK73VYCNHZHA7ENKCV37P6SUEO6XQBKPP",
        "distribution_account": "GBN4NNCDGJO4XW4KQU3CBIESUJWFVBUZPOKUZHT7W7WRB7CWOA7BXVQF",
        "significant_decimals": 2,
        "deposit" : {
          "enabled": true,
          "fee_minimum": 0,
          "fee_percent": 0,
          "min_amount": 1,
          "max_amount": 1000000
        },
        "withdraw": {
          "enabled": true,
          "fee_fixed": 0,
          "fee_percent": 0,
          "min_amount": 1,
          "max_amount": 1000000
        },
        "send": {
          "fee_fixed": 0,
          "fee_percent": 0,
          "min_amount": 1,
          "max_amount": 1000000
        },
        "sep31" : {
          "quotes_supported": true,
          "quotes_required": false,
          "sep12": {
            "sender": {
              "types": {
                "sep31-sender": {
                  "description": "U.S. citizens limited to sending payments of less than $10,000 in value"
                },
                "sep31-large-sender": {
                  "description": "U.S. citizens that do not have sending limits"
                },
                "sep31-foreign-sender": {
                  "description": "non-U.S. citizens sending payments of less than $10,000 in value"
                }
              }
            },
            "receiver": {
              "types": {
                "sep31-receiver": {
                  "description": "U.S. citizens receiving USD"
                },
                "sep31-foreign-receiver": {
                  "description": "non-U.S. citizens receiving USD"
                }
              }
            }
          },
          "fields": {
            "transaction": {
              "receiver_routing_number": {
                "description": "routing number of the destination bank account"
              },
              "receiver_account_number": {
                "description": "bank account number of the destination"
              },
              "type": {
                "description": "type of deposit to make",
                "choices": [
                  "SEPA",
                  "SWIFT"
                ]
              }
            }
          }
        },
        "sep38": {
          "exchangeable_assets": [
            "iso4217:USD"
          ]
        },
        "sep24_enabled": true,
        "sep31_enabled": true,
        "sep38_enabled": true
      },
      {
        "schema": "stellar",
        "code": "JPYC",
        "issuer": "GDQOE23CFSUMSVQK4Y5JHPPYK73VYCNHZHA7ENKCV37P6SUEO6XQBKPP",
        "distribution_account": "GBN4NNCDGJO4XW4KQU3CBIESUJWFVBUZPOKUZHT7W7WRB7CWOA7BXVQF",
        "significant_decimals": 4,
        "deposit" : {
          "enabled": true,
          "fee_minimum": 0,
          "fee_percent": 0,
          "min_amount": 1,
          "max_amount": 1000000
        },
        "withdraw": {
          "enabled": true,
          "fee_fixed": 0,
          "fee_percent": 0,
          "min_amount": 1,
          "max_amount": 1000000
        },
        "send": {
          "fee_fixed": 0,
          "fee_percent": 0,
          "min_amount": 1,
          "max_amount": 1000000
        },
        "sep31" : {
          "quotes_supported": true,
          "quotes_required": false,
          "sep12": {
            "sender": {
              "types": {
                "sep31-sender": {
                  "description": "U.S. citizens limited to sending payments of less than $10,000 in value"
                },
                "sep31-large-sender": {
                  "description": "U.S. citizens that do not have sending limits"
                },
                "sep31-foreign-sender": {
                  "description": "non-U.S. citizens sending payments of less than $10,000 in value"
                }
              }
            },
            "receiver": {
              "types": {
                "sep31-receiver": {
                  "description": "U.S. citizens receiving JPY"
                },
                "sep31-foreign-receiver": {
                  "description": "non-U.S. citizens receiving JPY"
                }
              }
            }
          },
          "fields": {
            "transaction": {
              "receiver_routing_number": {
                "description": "routing number of the destination bank account"
              },
              "receiver_account_number": {
                "description": "bank account number of the destination"
              },
              "type": {
                "description": "type of deposit to make",
                "choices": [
                  "SEPA",
                  "SWIFT"
                ]
              }
            }
          }
        },
        "sep38": {
          "exchangeable_assets": [
            "iso4217:USD"
          ]
        },
        "sep24_enabled": false,
        "sep31_enabled": true,
        "sep38_enabled": true
      },
      {
        "schema": "iso4217",
        "code": "USD",
        "deposit" : {
          "enabled": true,
          "fee_minimum": 0,
          "fee_percent": 0,
          "min_amount": 0,
          "max_amount": 10000
        },
        "withdraw": {
          "enabled": true,
          "fee_fixed": 0,
          "fee_percent": 0,
          "min_amount": 0,
          "max_amount": 10000
        },
        "send": {
          "fee_fixed": 0,
          "fee_percent": 0,
          "min_amount": 0,
          "max_amount": 10000
        },
        "sep38": {
          "exchangeable_assets": [
            "stellar:USDC:GDQOE23CFSUMSVQK4Y5JHPPYK73VYCNHZHA7ENKCV37P6SUEO6XQBKPP",
            "stellar:JPYC:GDQOE23CFSUMSVQK4Y5JHPPYK73VYCNHZHA7ENKCV37P6SUEO6XQBKPP"
          ],
          "country_codes": ["USA"],
          "decimals": 4,
          "sell_delivery_methods": [
            {
              "name": "WIRE",
              "description": "Send USD directly to the Anchor's bank account."
            }
          ],
          "buy_delivery_methods": [
            {
              "name": "WIRE",
              "description": "Have USD sent directly to your bank account."
            }
          ]
        },
        "sep24_enabled": false,
        "sep31_enabled": false,
        "sep38_enabled": true
      }
    ]
  }
