apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: fake-secret-store
  namespace: {{ .Values.namespace }}
spec:
  provider:
    fake:
      data:
        - key: {{ .Values.namespace }}/anchor-platform-secrets
          value: |
            {
              "POSTGRES_USER": "postgres",
              "POSTGRES_PASSWORD": "cdb1ajkMih",
              "SEP24_INTERACTIVE_URL_JWT_SECRET": "secret",
              "SEP24_MORE_INFO_URL_JWT_SECRET": "secret",
              "SEP10_JWT_SECRET": "secret",
              "SEP10_SIGNING_SEED": "SAX3AH622R2XT6DXWWSRIDCMMUCCMATBZ5U6XKJWDO7M2EJUBFC3AW5X",
              "EVENTS_QUEUE_KAFKA_USERNAME": "user1",
              "EVENTS_QUEUE_KAFKA_PASSWORD": "INfioH5l7N",
            }
        - key: {{ .Values.namespace}}/reference-server-secrets
          value: |
            {
              "POSTGRES_USER": "postgres",
              "POSTGRES_PASSWORD": "XgvqTkecnv",
              "SEP6_SECRET": "SAJW2O2NH5QMMVWYAN352OEXS2RUY675A2HPK5HEG2FRR2NXPYA4OLYN",
              "SEP24_INTERACTIVE_JWT_KEY": "secret_sep24_interactive_url_jwt_secret",
              "SEP24_SECRET": "SAJ34AG5XC7BWGK3GGQGCXERSEP7LZYXBBDMD33NMBASZVNKACEMNEIY",
              "PLATFORM_ANCHOR_SECRET": "myPlatformToAnchorSecret",
              "ANCHOR_PLATFORM_SECRET": "myAnchorToPlatformSecret",
            }