apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: fake-secret-store
spec:
  provider:
    fake:
      data:
        - key: "anchor-platform/anchor-platform-secrets"
          value: |
            {
              "POSTGRES_USER": "postgres",
              "POSTGRES_PASSWORD": "cdb1ajkMih",
              "SEP24_INTERACTIVE_URL_JWT_SECRET": "secret",
              "SEP24_MORE_INFO_URL_JWT_SECRET": "secret",
              "SEP10_JWT_SECRET": "secret",
              "SEP10_SIGNING_SEED": "SAX3AH622R2XT6DXWWSRIDCMMUCCMATBZ5U6XKJWDO7M2EJUBFC3AW5X",
              "EVENTS_QUEUE_KAFKA_USERNAME": "user1",
              "EVENTS_QUEUE_KAFKA_PASSWORD": "INfioH5l7N",
            }