apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: fake-secret-store
  namespace: {{ .Values.namespace }}
spec:
  provider:
    fake:
      data:
        - key: {{ .Values.namespace }}/anchor-platform-secrets
          value: |
            {
              "POSTGRES_USER": "postgres",
              "POSTGRES_PASSWORD": "cdb1ajkMih",
              "SEP24_INTERACTIVE_URL_JWT_SECRET": "c5457e3a349df9002117543efa7e316dd89e666a5ce6f33a0deb13e90f3f1e9d",
              "SEP24_MORE_INFO_URL_JWT_SECRET": "b106cce1e32ebe342ea1e38d363fe048c7dc9c1b773658f83e22b78125785d89",
              "SEP6_MORE_INFO_URL_JWT_SECRET": "3a614cf5da456aaad61dc7532f6c422fc2b833c0c05102b47b1ac2e8f0bff2e8",
              "SEP10_JWT_SECRET": "10bb04a51338a1df86c2e807f8fe36168cf9a480d70c233452ec7e198ab33b7c",
              "SEP10_SIGNING_SEED": "SAX3AH622R2XT6DXWWSRIDCMMUCCMATBZ5U6XKJWDO7M2EJUBFC3AW5X",
              "EVENTS_QUEUE_KAFKA_USERNAME": "user1",
              "EVENTS_QUEUE_KAFKA_PASSWORD": "INfioH5l7N",
            }
        - key: {{ .Values.namespace}}/reference-server-secrets
          value: |
            {
              "POSTGRES_USER": "postgres",
              "POSTGRES_PASSWORD": "XgvqTkecnv",
              "SEP6_SECRET": "SAJW2O2NH5QMMVWYAN352OEXS2RUY675A2HPK5HEG2FRR2NXPYA4OLYN",
              "SEP24_INTERACTIVE_JWT_KEY": "0005686076237201446d93d2ea92d1419647283e2acddbc2fffbf8d53db36b7d",
              "SEP24_SECRET": "SAJ34AG5XC7BWGK3GGQGCXERSEP7LZYXBBDMD33NMBASZVNKACEMNEIY",
              "PLATFORM_ANCHOR_SECRET": "myPlatformToAnchorSecret",
              "ANCHOR_PLATFORM_SECRET": "myAnchorToPlatformSecret",
            }