apiVersion: v1
appVersion: "1.0"
description: Anchor Platform Service Helm Chart
maintainers:
  - name: Philip Liu
    email: philip.liu@stellar.org
sources:
  - https://github.com/stellar/anchor-platform
name: sep
version: 1.0.0
icon: https://github.com/stellar/anchor-platform/blob/develop/icon.png