apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.fullName }}-svc-{{ .Values.services.eventProcessor.name }}
  labels:
    app.kubernetes.io/name: {{ .Values.fullName }}-event-processor
    helm.sh/chart: {{ include "common.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.services.eventProcessor.deployment.replicas | default 1 }}
  selector:
    matchLabels:
      app: {{ .Values.fullName }}-svc-{{ .Values.services.eventProcessor.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.fullName }}-svc-{{ .Values.services.eventProcessor.name }}
    spec:
      containers:
      - name: event-processor
        image: {{ .Values.container.image }}
        args: ["--event-processor"]
        imagePullPolicy: {{ .Values.container.imagePullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.services.sep.containerPort | default 8088 }}
          protocol: TCP
        volumeMounts:
          - name: config-volume
            mountPath: /config
            readOnly: true
        env:
        - name: STELLAR_ANCHOR_CONFIG
          value: file:/config/anchor-config.yaml
        - name: ASSETS_TYPE
          value: file
        - name: ASSETS_VALUE
          value: /config/assets.yaml
        - name: SECRET_DATA_USERNAME
          value: postgres # TODO: move to secret
        - name: SECRET_DATA_PASSWORD
          value: cdb1ajkMih # TODO: move to secret
        - name: SECRET_SEP24_INTERACTIVE_URL_JWT_SECRET
          value: secret
        - name: SECRET_SEP24_MORE_INFO_URL_JWT_SECRET
          value: secret
        - name: PLATFORM_API_BASE_URL
          value: {{ print "http://" .Values.fullName "-svc-" .Values.services.platform.name ":" .Values.services.platform.containerPort | default 8085 }}
        resources:
          requests:
            memory: {{ .Values.services.eventProcessor.deployment.resources.requests.memory }}
            cpu: {{ .Values.services.eventProcessor.deployment.resources.requests.cpu }}
          limits:
            memory: {{ .Values.services.eventProcessor.deployment.resources.limits.memory }}
            cpu: {{ .Values.services.eventProcessor.deployment.resources.limits.cpu }}
      volumes:
      - name: config-volume
        configMap:
          name: anchor-config
