apiVersion: apps/v1
kind: Deployment
metadata:
  name: ap-event-processor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ap-event-processor
  template:
    metadata:
      labels:
        app: ap-event-processor
    spec:
      containers:
      - name: event-processor
        image: anchor-platform:local
        args: ["--event-processor"]
        imagePullPolicy: Never
        ports:
        - name: http
          containerPort: 8088
          protocol: TCP
        volumeMounts:
          - name: config-volume
            mountPath: /config
            readOnly: true
        env:
        - name: STELLAR_ANCHOR_CONFIG
          value: file:/config/anchor-config.yaml
        - name: ASSETS_TYPE
          value: file
        - name: ASSETS_VALUE
          value: /config/assets.yaml
        - name: SECRET_DATA_USERNAME
          value: postgres # TODO: move to secret
        - name: SECRET_DATA_PASSWORD
          value: cdb1ajkMih # TODO: move to secret
        - name: SECRET_SEP24_INTERACTIVE_URL_JWT_SECRET
          value: secret
        - name: SECRET_SEP24_MORE_INFO_URL_JWT_SECRET
          value: secret
        resources:
          requessts:
            memory: 512Mi
            cpu: 500m
          limits:
            memory: 1Gi
            cpu: 1
      volumes:
      - name: config-volume
        configMap:
          name: anchor-config
