apiVersion: apps/v1
kind: Deployment
metadata:
  name: ap-sep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ap-sep
  template:
    metadata:
      labels:
        app: ap-sep
    spec:
      containers:
      - name: sep-server
        image: anchor-platform:local
        args: ["--sep-server"]
        imagePullPolicy: Never
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        startupProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 120
          failureThreshold: 10
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 120
          failureThreshold: 2
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 120
          periodSeconds: 30
        volumeMounts:
        - name: config-volume
          mountPath: /config
          readOnly: true
        env:
        - name: STELLAR_ANCHOR_CONFIG
          value: file:/config/anchor-config.yaml
        - name: ASSETS_TYPE
          value: file
        - name: ASSETS_VALUE
          value: /config/assets.yaml
        - name: SECRET_DATA_USERNAME
          value: postgres # TODO: move to secret
        - name: SECRET_DATA_PASSWORD
          value: cdb1ajkMih # TODO: move to secret
        - name: SECRET_SEP24_INTERACTIVE_URL_JWT_SECRET
          value: secret
        - name: SECRET_SEP24_MORE_INFO_URL_JWT_SECRET
          value: secret
        - name: SECRET_SEP10_JWT_SECRET
          value: secret
        - name: SECRET_SEP10_SIGNING_SEED
          value: SAX3AH622R2XT6DXWWSRIDCMMUCCMATBZ5U6XKJWDO7M2EJUBFC3AW5X
        resources:
          requests:
            memory: 512Mi
            cpu: 500m
          limits:
            memory: 1Gi
            cpu: 1
      volumes:
      - name: config-volume
        configMap:
          name: anchor-config        
