apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.fullName }}-svc-{{ .Values.services.sep.name }}
  labels:
    {{- if .Values.services.sep.labels }}
      {{- range $key, $value := .Values.services.sep.labels }}
        {{ $key }}: {{ $value | quote }}
      {{- end }}
    {{- end}}
    app.kubernetes.io/name: {{ .Values.fullName }}-sep
    helm.sh/chart: {{ $.Chart.Name }}-{{ $.Chart.Version }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.services.sep.type | default "ClusterIP" }}
  ports:
    - protocol: TCP
      port: {{ .Values.services.sep.servicePort | default 8080 }}
      targetPort: {{ .Values.services.sep.containerPort | default 8080 }}
  selector:
    app: {{ .Values.fullName }}-svc-{{ .Values.services.sep.name }}
