ACCOUNTS = []
VERSION = "0.1.0"
NETWORK_PASSPHRASE = "Test SDF Network ; September 2015"
SIGNING_KEY = "GCHLHDBOKG2JWMJQBTLSL5XG6NO7ESXI2TAQKZXCXWXB5WI2X6W233PR"

WEB_AUTH_ENDPOINT = "http://localhost:8080/auth"
KYC_SERVER = "http://localhost:8080/sep12"
TRANSFER_SERVER_SEP0024 = "http://localhost:8080/sep24"
DIRECT_PAYMENT_SERVER = "http://localhost:8080/sep31"
ANCHOR_QUOTE_SERVER = "http://localhost:8080/sep38"

[[CURRENCIES]]
code = "USDC"
issuer = "GBBD47IF6LWK7P7MDEVSCWR7DPUWV3NY3DTQEVFL4NAT4AQH3ZLLFLA5"
status = "test"
is_asset_anchored = true
anchor_asset_type = "fiat"
desc = "A test USDC issued by Circle."