version: '2.4'
services:
  platform:
    image: stellar/anchor-platform:edge
    command: --sep-server
    volumes:
      - ../config:/config
    ports:
      - "8080:8080" # sep-server
      - "8082:8082" # Java management server

  reference-server:
    image: stellar/anchor-platform:edge
    command: "--anchor-reference-server"
    environment:
      - REFERENCE_SERVER_CONFIG_ENV=file:/config/java-reference-server-config.yaml
    volumes:
      - ../config:/config
    ports:
      - "8081:8081"

  sep24-reference-ui:
    image: stellar/sep24-reference-ui
    ports:
      - "3000:80"

  observer:
    image: stellar/anchor-platform:edge
    build:
      context: ../../../../../integration-tests/src/test
      dockerfile: integration-tests/docker-compose-configs/Dockerfile
    command: "--stellar-observer"
    volumes:
      # add mounts for the new config directory
      - ../config:/config
    extra_hosts:
      - "host.docker.internal:host-gateway"

  kafka:
    platform: linux/x86_64
    image: confluentinc/cp-kafka:6.1.9
    ports:
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  zookeeper:
    platform: linux/x86_64
    image: confluentinc/cp-zookeeper:6.1.9
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  db:
    image: postgres:15.2-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
