fullName: sep24-reference-ui
namespace: default

container:
  image: sep24-reference-ui:local
  imagePullPolicy: Never

services:
  ref:
    containerPort: 3000
    servicePort: 3000
    type: ClusterIP
    name: sep24-reference-ui
    deployment:
      replicas: 1
      resources:
        requests:
          memory: 512Mi
          cpu: 500m
        limits:
          memory: 1Gi
          cpu: 1
ingress:
  name: ingress-sep24-reference-ui
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
