items:
  - name: referenceCustodial
    type: custodial
    signing_keys:
      - GDJLBYYKMCXNVVNABOE66NYXQGIA5AC5D223Z2KF6ZEYK4UBCA7FKLTG
  - name: stellar_anchor_tests
    type: custodial
    signing_keys:
      - GDOHXZYP5ABGCTKAEROOJFN6X5GY7VQNXFNK2SHSAD32GSVMUJBPG75E
  - name: reference
    type: noncustodial
    domains:
      - wallet-server:8092
    callback_urls:
      sep6: http://wallet-server:8092/callbacks/sep6
      sep24: http://wallet-server:8092/callbacks/sep24
      sep31: http://wallet-server:8092/callbacks/sep31
      sep12: http://wallet-server:8092/callbacks/sep12
