items:
  - name: referenceCustodial
    type: custodial
    signing_keys:
      - GDJLBYYKMCXNVVNABOE66NYXQGIA5AC5D223Z2KF6ZEYK4UBCA7FKLTG
      - GD4C2QRT7YL4WJFJPYQCYRXEDBB7ERHC3XZGWR6KXKRHPEFXXNXIVNFY
      - GC56VTOVOJDRQAJRYLZW6DLQGVTQSYDTZU7ISNIZ2VJIE3FYWI2HMD5G
      - GDC2U5GRKUSPGV5XENLBWKQZH2C4PG7ZEVMQOUA2QZKIRXE5FYYEMEF7
      - GASI56WX7UKIDFPZRCQEI4OQE3V3QBGXEOB4ZY6ZMU5MZXPHQHIDA7JU
    destination_accounts:
      - GAIUIZPHLIHQEMNJGSZKCEUWHAZVGUZDBDMO2JXNAJZZZVNSVHQCEWJ4
    callback_urls:
      sep6: http://wallet-server:8092/callbacks/sep6
      sep24: http://wallet-server:8092/callbacks/sep24
      sep31: http://wallet-server:8092/callbacks/sep31
      sep12: http://wallet-server:8092/callbacks/sep12
  - name: stellar_anchor_tests
    type: custodial
    signing_keys:
      - GDOHXZYP5ABGCTKAEROOJFN6X5GY7VQNXFNK2SHSAD32GSVMUJBPG75E
  - name: reference
    type: noncustodial
    domains:
      - wallet-server:8092
    callback_urls:
      sep6: http://wallet-server:8092/callbacks/sep6
      sep24: http://wallet-server:8092/callbacks/sep24
      sep31: http://wallet-server:8092/callbacks/sep31
      sep12: http://wallet-server:8092/callbacks/sep12
  - name: circleWallet
    type: noncustodial
    domains:
      - circlewallet.example.com
    callback_urls:
      sep24: http://localhost:19091/callbacks/sep24
