apiVersion: v1
appVersion: "1.0"
description: Fake secret store for local testing
maintainers:
  - name: Philip Liu
    email: philip.liu@stellar.org
sources:
  - https://github.com/stellar/anchor-platform
name: ap-secret-store
version: 0.1.0
