stellar:
  anchor:
    # Configure the application from this file after it is loaded in memory
    # If `config` is in-memory, the yaml file contains all settings for the server.
    config: in-memory
    app-config:
      type: config-spring-property                # Activate [config-spring-property] module
      settings: app-config                        # The location of the configuration data
    data-access:
      type: data-spring-jdbc                      # Activate [config-spring-jdbc] module.
      settings: data-spring-jdbc-h2               # The location of the configuration data in this file.
    logging:
      type: logging-logback
      settings: logging-logback-settings

#
# Application settings
#
app-config:
  # general
  app:
    stellarNetworkPassphrase: Test SDF Network ; September 2015
    hostUrl: https://anchor-sep-pr423.previews.kube001.services.stellar-ops.com
    languages: en
    horizonUrl: https://horizon-testnet.stellar.org
    assets: assets-test.json
    jwtSecretKey: ${JWT_SECRET}

  integration-auth:
    authType: JWT_TOKEN
    platformToAnchorSecret: ${PLATFORM_TO_ANCHOR_SECRET}
    anchorToPlatformSecret: ${ANCHOR_TO_PLATFORM_SECRET}
    expirationMilliseconds: 30000

  # sep-1
  sep1:
    enabled: true
    stellarFile: file:/config/stellar-wks.toml

  # sep-10
  sep10:
    enabled: true
    homeDomain: anchor-sep-pr423.previews.kube001.services.stellar-ops.com
    clientAttributionRequired: false
    clientAttributionAllowList: lobstr.co,preview.lobstr.co # use this if we want to white list
    # clientAttributionDenyList: # use this if we want to black list.
    authTimeout: 900
    jwtTimeout: 86400
    signingSeed: ${SEP10_SIGNING_SEED}

  # sep-12
  sep12:
    enabled: true
    customerIntegrationEndpoint: https://anchor-ref-pr423.previews.kube001.services.stellar-ops.com

  # sep-24
  sep24:
    enabled: false

  # sep-31
  sep31:
    enabled: true
    feeIntegrationEndPoint: https://anchor-ref-pr423.previews.kube001.services.stellar-ops.com
    paymentType: STRICT_SEND
    depositInfoGeneratorType: self

  # sep-38
  sep38:
    enabled: true
    quoteIntegrationEndPoint: https://anchor-ref-pr423.previews.kube001.services.stellar-ops.com

  circle:
    circleUrl: https://api-sandbox.circle.com
    apiKey: ${CIRCLE_API_KEY} # circle API key

  payment-gateway:
    #
    # Payment Circle configurations
    #
    circle:
      name: "circle"
      enabled: true

    #
    # Payment Stellar configurations
    #
    stellar:
      enabled: false
      name: "stellar"
      horizonUrl: https://horizon-testnet.stellar.org
      secretKey: ${PAYMENT_GATEWAY_STELLAR_SECRET_KEY} # stellar account secret key

  circle-payment-observer:
    enabled: true
    horizonUrl: https://horizon-testnet.stellar.org
    stellarNetwork: TESTNET # TESTNET or PUBLIC
    trackedWallet: all

  event:
    # If enabled, publish Events to a queue (publisherType)
    # publisherType - the type of queue to use for event publishing
    enabled: true
    publisherType: kafka

  kafka.publisher:
    # kafkaBootstrapServer - the Kafka server used to bootstrap setup
    # If useSingleQueue, all events are published to a single queue
    #   (specified in eventTypeToQueue.all)
    # eventTypeToQueue - a map of the event type to the queue name messages are published to
    bootstrapServer: anchor-platform-kafka.anchor-platform-dev.svc.cluster.local:9092
    useSingleQueue: false
    eventTypeToQueue:
      all: pr423_ap_event_single_queue
      quoteCreated: pr423_ap_event_quote_created
      transactionCreated: pr423_ap_event_transaction_created
      transactionStatusChanged: pr423_ap_event_transaction_status_changed
      transactionError: pr423_ap_event_transaction_error

#
# Spring Data JDBC settings
#
data-spring-jdbc-sqlite:
  spring.jpa.database-platform: org.stellar.anchor.platform.sqlite.SQLiteDialect
  spring.jpa.hibernate.ddl-auto: update
  spring.jpa.generate-ddl: true
  spring.jpa.hibernate.show_sql: false
  spring.datasource.url: jdbc:sqlite:anchor-proxy.db
  spring.datasource.driver-class-name: org.sqlite.JDBC
  spring.datasource.max-active: 1 # For SQLite, set this to 1 to avoid database file lock exception.
  spring.datasource.initial-size: 1 # For SQLite, set this to 1 to avoid database file lock exception.
  spring.datasource.username: ${SQLITE_USERNAME}
  spring.datasource.password: ${SQLITE_PASSWORD}
  spring.mvc.converters.preferred-json-mapper: gson

data-spring-jdbc-h2:
  spring.datasource.url: jdbc:h2:mem:test
  spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.H2Dialect
  spring.liquibase.enabled: false

#
# Spring framework configurations
#
spring:
  logging:
    level:
      root: INFO
      org.springframework: INFO
      org.springframework.web.filter: INFO
      org.stellar: INFO
  mvc:
    async.request-timeout: 6000