name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-push-anchor-platform:
    runs-on: ubuntu-latest
    name: Push stellar/anchor-platform:sha to DockerHub
    steps:
    - uses: actions/checkout@v3
    
    - name: Get image tag (short sha)
      shell: bash
      id: get_tag
      run: echo ::set-output name=TAG::$(git rev-parse --short ${{ github.sha }} )

    - name: Login to DockerHub
      uses: docker/login-action@bb984efc561711aaa26e433c32c3521176eae55b
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push to DockerHub
      uses: docker/build-push-action@7f9d37fa544684fb73bfe4835ed7214c255ce02b
      with:
        # TODO: Commented out until we disable the CircleCI jobs
        # push: true
        tags: stephenxlm/anchor-platform:${{ steps.get_tag.outputs.TAG }}
        file: Dockerfile
