name: End-2-End Integration Tests

on:
  workflow_dispatch:
  workflow_call: # Allows this workflow to be called from another workflow
  pull_request:
    branches:
      - main
      - develop
      - 'release/**'
      - 'releases/**'
      - 'hotfix/**'

jobs:
  end_to_end_tests:
    runs-on: ubuntu-20.04
    env:
        E2E_SECRET: "SBQIOKSYVFEK5MKGMMF72MB2LEGITKUVMCSOMOYFAZUFNDIHJ6AAZIG3"
        OMNIBUS_ALLOWLIST_KEYS: "GAFOGZPLLOUQMI5C63PV7V3KCYBJF3R6I4BTLQK65YLT72SR4FKK6PB2"
        SECRET_SEP10_SIGNING_SEED: "SAKXNWVTRVR4SJSHZUDB2CLJXEQHRT62MYQWA2HBB7YBOTCFJJJ55BZF"

    steps:
      - uses: actions/checkout@v3

      - name: Build images for end-to-end tests
        run: make build-docker-compose-tests

      - name: Run end-to-end tests (Default Config)
        run: make run-e2e-test-default-config

      - name: Run end-to-end tests (Unique Address)
        run: make run-e2e-test-unique-address

      - name: Run end-to-end tests (Allowlist)
        run: make run-e2e-test-allowlist
