name: Integration Tests

on:
  workflow_call: # Allows this workflow to be called from another workflow
  push:
    branches: 
      - main
      - develop
      - 'release/**'
      - 'releases/**'
      - 'hotfix/**'

jobs:
  end_to_end_tests:
    runs-on: ubuntu-latest
    env:
        E2E_SECRET: ${{ secrets.E2E_SECRET }}
        OMNIBUS_ALLOWLIST_KEYS: ${{ secrets.OMNIBUS_ALLOWLIST_KEYS }}

    steps:
      - uses: actions/checkout@v3

      - name: Build images for end-to-end tests
        run: make build-docker-compose-tests

      - name: Run end-to-end tests (Default Config)
        run: make run-e2e-test-default-config

      - name: Run end-to-end tests (Unique Address)
        run: make run-e2e-test-unique-address

      - name: Run end-to-end tests (Allowlist)
        run: make run-e2e-test-allowlist
