# This workflow will build a docker image and push to docker hub
# This workflow is triggered:
#   1. When commits are pushed or merged onto `develop` branch
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

name: Push/Merge to `develop` Branch

on:
  push:
    # when commits are pushed or pull requests merged onto `develop` branch
    branches: [ develop, chore/fix-docker-push ]

jobs:
  gradle_build:
    uses: ./.github/workflows/sub_gradle_build.yml

  rust_build:
    uses: ./.github/workflows/sub_rust_build.yml

#  essential_tests:
#    needs: [ gradle_build ]
#    uses: ./.github/workflows/sub_essential_tests.yml
#    concurrency:
#      group: ap-test-job
#      cancel-in-progress: false
#
#  extended_tests:
#    needs: [ gradle_build, essential_tests ]
#    uses: ./.github/workflows/sub_extended_tests.yml
#    concurrency:
#      group: ap-test-job
#      cancel-in-progress: false

  codeql_analysis:
    uses: ./.github/workflows/sub_codeql_analysis.yml

  build_and_push_docker_image:
    name: Push to DockerHub
    needs: [ gradle_build ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@bb984efc561711aaa26e433c32c3521176eae55b
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get current date
        id: get_date
        run: echo "DATE=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Calculate Github SHA
        shell: bash
        id: get_sha
        run: echo "SHA=$(git rev-parse --short ${{ github.sha }} )" >> $GITHUB_OUTPUT

      - name: Build and push Docker images
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          # Optional but often useful to quiet SBOM/provenance warnings on multi-arch
          provenance: false
          platforms: linux/amd64,linux/arm64
          tags: |
            stellar/anchor-platform:edge,stellar/anchor-platform:edge-${{ steps.get_date.outputs.DATE }}-${{ steps.get_sha.outputs.SHA }}
          # Optional: add build cache for faster rebuilds
          cache-from: type=gha
          cache-to: type=gha,mode=max

  complete:
    if: always()
    needs: [ essential_tests, extended_tests, rust_build, build_and_push_docker_image ]
    runs-on: ubuntu-latest
    steps:
      - if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')
        run: exit 1
