# This workflow will build a docker image and push to docker hub
# This workflow is triggered:
#   1. When commits are pushed or merged onto `develop` branch
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

name: Push/Merge to `develop` Branch

on:
  pull_request:
  push:
    # when commits are pushed or pull requests merged onto `develop` branch
    branches: [ develop ]

jobs:
  build_and_push_docker_image_amd64:
    name: Push to DockerHub - AMD64
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      # Use a Buildx builder with the docker-container driver (required for --platform)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true
          driver: docker-container
          driver-opts: |
            image=moby/buildkit:latest

      - name: Get current date
        id: get_date
        run: echo "DATE=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Calculate Github SHA
        shell: bash
        id: get_sha
        run: echo "SHA=$(git rev-parse --short ${{ github.sha }} )" >> $GITHUB_OUTPUT

      - name: Login to DockerHub
        uses: docker/login-action@bb984efc561711aaa26e433c32c3521176eae55b
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker images - AMD64
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64
          tags: |
            stellar/anchor-platform:edge,stellar/anchor-platform:edge-${{ steps.get_date.outputs.DATE }}-${{ steps.get_sha.outputs.SHA }}
          # add build cache for faster rebuilds
          cache-from: type=gha
          cache-to: type=gha,mode=max

  build_and_push_docker_image_arm64:
    name: Push to DockerHub
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4

      # Use a Buildx builder with the docker-container driver (required for --platform)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true
          driver: docker-container
          driver-opts: |
            image=moby/buildkit:latest

      - name: Get current date
        id: get_date
        run: echo "DATE=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Calculate Github SHA
        shell: bash
        id: get_sha
        run: echo "SHA=$(git rev-parse --short ${{ github.sha }} )" >> $GITHUB_OUTPUT

      - name: Login to DockerHub
        uses: docker/login-action@bb984efc561711aaa26e433c32c3521176eae55b
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker images - AMD64
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/arm64
          tags: |
            stellar/anchor-platform:edge,stellar/anchor-platform:edge-${{ steps.get_date.outputs.DATE }}-${{ steps.get_sha.outputs.SHA }}
          # add build cache for faster rebuilds
          cache-from: type=gha
          cache-to: type=gha,mode=max

  complete:
    if: always()
    needs: [ build_and_push_docker_image_amd64, build_and_push_docker_image_arm64 ]
    runs-on: ubuntu-latest
    steps:
      - if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')
        run: exit 1
