name: Pull Request Comments

on:
  issue_comment:
    types: [ created, edited ]

jobs:
  run-extended-tests:
    if: github.event.issue.pull_request && contains(github.event.comment.body, '/run-extended-tests')
    uses: ./.github/workflows/sub_extended_tests.yml

  run-essential-tests:
    if: github.event.issue.pull_request && contains(github.event.comment.body, '/run-essential-tests')
    uses: ./.github/workflows/sub_essential_tests.yml

  run-codeql-analysis:
    if: github.event.issue.pull_request && contains(github.event.comment.body, '/run-codeql-analysis')
    uses: ./.github/workflows/sub_codeql_analysis.yml

  run-jacoco-report:
    if: github.event.issue.pull_request && contains(github.event.comment.body, '/run-jacoco-report')
    uses: ./.github/workflows/sub_jacoco_report.yml
    with:
      forceRebuild: true
