name: Release Published

on:
  workflow_dispatch:
  release:
    types: [ created, edited ]

permissions:
  contents: read

jobs:
  check_release_tag:
    runs-on: ubuntu-latest
    name: Validate Release Tag
    steps:
      - uses: actions/checkout@v4

      - name: Get EXPECTED_RELEASE_TAG
        shell: bash
        run: echo "EXPECTED_RELEASE_TAG=$(./gradlew -q printVersionName)" >> "$GITHUB_ENV"

      - name: Fail if the release version and the project version do not match
        if: ${{ github.event.release.tag_name != env.EXPECTED_RELEASE_TAG }}
        run: |
          echo "The release tag is invalid: [${{ github.event.release.tag_name }}]"
          echo "The expected release tag is: [${{ env.EXPECTED_RELEASE_TAG }}]"
          echo "The release tag must match project version."
          exit 1

  build_docker_image_amd64:
    name: Build Docker Image - AMD64
    needs: [ check_release_tag ]
    runs-on: ubuntu-24.04
    outputs:
      digest: ${{ steps.build.outputs.digest }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true
          driver: docker-container
          driver-opts: |
            image=moby/buildkit:latest

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push by digest - AMD64
        id: build
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64
          build-args: |
            TARGETARCH=amd64
          outputs: type=image,name=stellar/anchor-platform,push-by-digest=true,name-canonical=true,push=true
          cache-from: type=gha
          cache-to: type=gha,mode=max

  build_docker_image_arm64:
    name: Build Docker Image - ARM64
    needs: [ check_release_tag ]
    # Having a separate job for ARM64 helps to reduce overall build time.
    # The multi-arch build takes longer if running the arm build on an amd64 runner via emulation.
    runs-on: ubuntu-24.04-arm
    outputs:
      digest: ${{ steps.build.outputs.digest }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true
          driver: docker-container
          driver-opts: |
            image=moby/buildkit:latest

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push by digest - ARM64
        id: build
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/arm64
          build-args: |
            TARGETARCH=arm64
          outputs: type=image,name=stellar/anchor-platform,push-by-digest=true,name-canonical=true,push=true
          cache-from: type=gha
          cache-to: type=gha,mode=max

  create_multi_arch_manifest:
    name: Create Multi-Arch Manifest
    needs: [ build_docker_image_amd64, build_docker_image_arm64 ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get EXPECTED_RELEASE_TAG
        shell: bash
        run: echo "EXPECTED_RELEASE_TAG=$(./gradlew -q printVersionName)" >> "$GITHUB_ENV"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Create and push multi-arch manifest for version tag
        run: |
          docker buildx imagetools create -t stellar/anchor-platform:${{ env.EXPECTED_RELEASE_TAG }} \
            stellar/anchor-platform@${{ needs.build_docker_image_amd64.outputs.digest }} \
            stellar/anchor-platform@${{ needs.build_docker_image_arm64.outputs.digest }}

      - name: Create and push multi-arch manifest for latest tag
        run: |
          docker buildx imagetools create -t stellar/anchor-platform:latest \
            stellar/anchor-platform@${{ needs.build_docker_image_amd64.outputs.digest }} \
            stellar/anchor-platform@${{ needs.build_docker_image_arm64.outputs.digest }}

  complete:
    if: always()
    needs: [ check_release_tag, build_docker_image_amd64, build_docker_image_arm64, create_multi_arch_manifest ]
    runs-on: ubuntu-latest
    steps:
      - if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')
        run: exit 1