name: Release Published

on:
  release:
    types:
      - published

jobs:
  tests:
    uses: ./.github/workflows/basic_tests.yml  # execute the callable basic_tests.yml

  end_to_end_tests:
    uses: ./.github/workflows/end_to_end_tests.yml  # execute the callable end_to_end_tests.yml
  
  build_and_push_docker_image:
    name: Push to DockerHub # stellar/anchor-platform:{VERSION}
    needs: [tests]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Login to DockerHub
      uses: docker/login-action@bb984efc561711aaa26e433c32c3521176eae55b
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push to DockerHub
      uses: docker/build-push-action@7f9d37fa544684fb73bfe4835ed7214c255ce02b
      with:
        push: true
        tags: stellar/anchor-platform:${{ github.event.release.tag_name }},stellar/anchor-platform:latest
        file: Dockerfile

  complete:
    if: always()
    needs: [tests, build_and_push_docker_image]
    runs-on: ubuntu-latest
    steps:
    - if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')
      run: exit 1
