name: "Release from the Develop Branch"

on:
  push:
    branches: 
      - develop

jobs:
  tests:
    uses: ./.github/workflows/basic_tests.yml  # use the callable tests job to run tests
  
  build_and_push_docker_image:
    needs: [tests]
    runs-on: ubuntu-latest
    name: Push stellar/anchor-platform:sha to DockerHub
    steps:
    - uses: actions/checkout@v3
    
    - name: Get image SHA
      shell: bash
      id: get_sha
      run: echo ::set-output name=SHA::$(git rev-parse --short ${{ github.sha }} )

    - name: Login to DockerHub
      uses: docker/login-action@bb984efc561711aaa26e433c32c3521176eae55b
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push to DockerHub
      uses: docker/build-push-action@7f9d37fa544684fb73bfe4835ed7214c255ce02b
      with:
        push: true
        tags: stellar/anchor-platform:${{ steps.get_sha.outputs.SHA }},stellar/anchor-platform:edge
        file: Dockerfile

  complete:
    if: always()
    needs: [tests, build_and_push_docker_image]
    runs-on: ubuntu-latest
    steps:
    - if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')
      run: exit 1