name: Build Soroban Contracts

on:
  workflow_dispatch:
  workflow_call:

jobs:
  cargo_build:
    name: Cargo Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: soroban
    permissions:
      contents: read
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          show-progress: false
      - name: Cargo Build
        run: cargo build --verbose
      - name: Clippy
        run: cargo clippy -- -Dwarnings
      - name: Run tests
        run: cargo test --verbose
