name: Run Essential Tests Workflow

on:
  workflow_dispatch:
  workflow_call:

concurrency:
  group: ap-test-job
  cancel-in-progress: false

env:
  # Anchor Platform secrets
  SECRET_SEP10_SIGNING_SEED: ${{ vars.SECRET_SEP10_SIGNING_SEED }}
  APP__PAYMENT_SIGNING_SEED: ${{ vars.APP__PAYMENT_SIGNING_SEED }}
  SECRET__KEY: ${{ vars.SECRET__KEY }}

  # Test secrets
  TEST_CLIENT_WALLET_SECRET: ${{ vars.TEST_CLIENT_WALLET_SECRET }}
  TEST_CLIENT_SMART_WALLET_ACCOUNT: ${{ vars.TEST_CLIENT_SMART_WALLET_ACCOUNT }}
  TEST_CLIENT_WALLET_EXTRA_SIGNER_1_SECRET: ${{ vars.TEST_CLIENT_WALLET_EXTRA_SIGNER_1_SECRET }}
  TEST_CLIENT_WALLET_EXTRA_SIGNER_2_SECRET: ${{ vars.TEST_CLIENT_WALLET_EXTRA_SIGNER_2_SECRET }}
  TEST_WITHDRAW_FUND_CLIENT_SECRET_1: ${{ vars.TEST_WITHDRAW_FUND_CLIENT_SECRET_1 }}
  TEST_WITHDRAW_FUND_CLIENT_SECRET_2: ${{ vars.TEST_WITHDRAW_FUND_CLIENT_SECRET_2 }}
  TEST_DEPOSIT_FUND_CLIENT_SECRET_1: ${{ vars.TEST_DEPOSIT_FUND_CLIENT_SECRET_1 }}
  TEST_DEPOSIT_FUND_CLIENT_SECRET_2: ${{ vars.TEST_DEPOSIT_FUND_CLIENT_SECRET_2 }}

jobs:
  suite_tests:
    name: Run ${{ matrix.suite }} Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        suite: [Infrastructure, Sep10, Sep12, Sep38, Sep6, Sep24, Sep31, Sep45, Platform]
    steps:
      - name: Setup Anchor Platform
        uses: ./.github/actions/setup-anchor-platform

      - name: Run ${{ matrix.suite }} Tests
        env:
          TEST_PROFILE_NAME: default
          RUN_DOCKER: false
          ANCHOR_DOMAIN: http://host.docker.internal:8080
        run: |
          cd /home/runner/anchor-platform
          ./gradlew clean run${{ matrix.suite }}Tests

      - name: Upload ${{ matrix.suite }} Tests report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.suite }}-tests-report
          path: /home/runner/anchor-platform/essential-tests/build/reports/

  stellar_validation:
    name: Run Stellar Validation Tool
    needs: suite_tests
    runs-on: ubuntu-latest
    steps:
      - name: Setup Anchor Platform
        uses: ./.github/actions/setup-anchor-platform

      - name: Pull Stellar Validation Tests Docker Image
        run: docker pull stellar/anchor-tests:latest

      - name: Run Stellar validation tool
        run: |
          docker run --network host -v /home/runner/anchor-platform/platform/src/test/resources://config stellar/anchor-tests:latest --home-domain http://host.docker.internal:8080 --seps 1 6 10 12 24 31 38 --sep-config //config/stellar-anchor-tests-sep-config.json --asset-code USDC --verbose
