name: end-2-end Integration Tests

on:
  # allows this workflow to be called from another workflow
  workflow_dispatch:
  workflow_call:

jobs:
  end_to_end_tests:
    runs-on: ubuntu-20.04
    env:
      E2E_SECRET: ${{ secrets.E2E_SECRET }}
      OMNIBUS_ALLOWLIST_KEYS: ${{ secrets.OMNIBUS_ALLOWLIST_KEYS }}
      SECRET_SEP10_SIGNING_SEED: ${{ secrets.SECRET_SEP10_SIGNING_SEED }}

    steps:
      - uses: actions/checkout@v3

      - name: Build images for end-to-end tests
        run: make build-docker-compose-tests

      - name: Run end-to-end tests (Default Config)
        run: make run-e2e-test-default-config

      - name: Run end-to-end tests (Unique Address)
        run: make run-e2e-test-unique-address

      - name: Run end-to-end tests (Allowlist)
        run: make run-e2e-test-allowlist
