name: Build Anchor Platform Runnable Jar

on:
  workflow_dispatch:
  workflow_call:

jobs:
  gradle_build:
    name: Gradle Build and Unit Tests
    runs-on: ubuntu-latest-16-cores
    permissions:
      contents: read
      # write to PR  permission is required for jacocoTestReport Action to update comment
      pull-requests: write
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          show-progress: false

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Gradle Build with unit tests only
        env:
          run_docker: false
        run: ./gradlew build jacocoTestReport -x essential-tests:test -x extended-tests:test --no-daemon --stacktrace -x spotlessApply -x spotlessKotlinApply -x javadoc -x javadocJar -x sourcesJar -x distTar -x distZip -x shadowJar -x shadowDistZip -x shadowDistTar -x bootDistTar -x bootDistZip

      - name: Archive Project Folder
        run: |
          cd /home/runner/work/java-stellar-anchor-sdk
          tar -cf /home/runner/java-stellar-anchor-sdk.tar ./java-stellar-anchor-sdk

      - name: Upload java-stellar-anchor-sdk.tar to GitHub Artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: java-stellar-anchor-sdk-tar
          path: |
            /home/runner/java-stellar-anchor-sdk.tar
