# This workflow will build a Java project with Gradle.
# This workflow is triggered:
#   On all pull request events
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

name: Pull Request Workflow

on:
  pull_request:

jobs:
  gradle_test_and_build:
    uses: ./.github/workflows/sub_gradle_test_and_build.yml

  complete:
    if: always()
    needs: [ gradle_test_and_build ]
    runs-on: ubuntu-22.04
    steps:
      - if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')
        run: exit 1
